# Generated by Django 4.1.1 on 2022-09-10 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_test',
            new_name='event_text',
        ),
    ]
