# Generated by Django 4.1.1 on 2022-09-10 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('date', models.DateTimeField()),
                ('image', models.ImageField(upload_to='post_images/')),
                ('text', models.CharField(max_length=8000)),
            ],
        ),
    ]
